load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "bullshit-test",
    srcs = ["gui.cpp"],
    deps = [
        "//dom",
        "//html",
        "//http",
        "@glib",
    ],
)
