on: [push, pull_request]
name: ci
jobs:
  linux-ci:
    name: linux-${{ matrix.name }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gcc
            compiler: gcc
            version: 10
            bazel: --config gcc

          - name: clang-12
            compiler: clang
            version: 12
            bazel: --config clang --run_under="valgrind --leak-check=full --errors-for-leak-kinds=all --error-exitcode=1 --track-origins=yes --show-leak-kinds=all"
            apt: valgrind

          - name: clang-13
            compiler: clang
            version: 13
            bazel: --config clang13

          - name: clang-asan
            compiler: clang
            version: 13
            bazel: --config clang13 --config asan

          - name: clang-ubsan
            compiler: clang
            version: 13
            bazel: --config clang13 --config ubsan

          - name: clang-libc++
            compiler: clang
            version: 13
            bazel: --config clang13 --config libc++
            apt: libc++abi-13-dev libc++-13-dev

    steps:
    - name: Prepare clang install
      if: startsWith(matrix.compiler, 'clang') && matrix.version == 13
      uses: myci-actions/add-deb-repo@10
      with:
        repo: deb http://apt.llvm.org/focal/ llvm-toolchain-focal-${{ matrix.version }} main
        repo-name: llvm-toolchain-focal-${{ matrix.version }}
        keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
    - name: Setup gcc
      if: startsWith(matrix.compiler, 'gcc')
      run: |
        echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
        echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
    - name: Setup clang
      if: startsWith(matrix.compiler, 'clang')
      run: |
        echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
        echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Install
      run: |
          sudo apt update
          sudo apt install libxrandr-dev libgl-dev ${{ matrix.compiler }}-${{ matrix.version }} ${{ matrix.apt }}
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64 --output-document=bazel
    - name: Build
      run: bazel build //... ${{ matrix.bazel }}
    - name: Test
      run: bazel test //... ${{ matrix.bazel }}
    - name: Run
      run: bazel run browser:tui ${{ matrix.bazel }}

  windows-msvc:
    runs-on: windows-2019
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: curl --output bazel.exe https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-windows-amd64.exe
    - name: Build
      run: bazel build ///... --config msvc
    - name: Test
      run: bazel test ///... --config msvc
    - name: Run
      run: bazel run browser:tui --config msvc

  clang-format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: sudo apt install clang-format-12
    - name: Format
      run: find . -name *.h -o -name *.cpp | xargs clang-format-12 -style=file -i
    - name: Check
      run: git diff --exit-code

  buildifier:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
          wget https://github.com/bazelbuild/buildtools/releases/download/4.2.2/buildifier
          sudo chmod +x buildifier
    - name: Check
      run: ./buildifier --lint=warn --warnings=all -mode diff WORKSPACE $(find . -type f -iname *.BUILD -or -iname BUILD)

  linux-cmake-gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
          sudo apt install libxrandr-dev libgl-dev libudev-dev libfreetype-dev libasio-dev libfmt-dev libspdlog-dev
          echo "CC=gcc-10" >> $GITHUB_ENV
          echo "CXX=g++-10" >> $GITHUB_ENV
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-linux-amd64 --output-document=bazel
    - name: Configure
      run:  cmake -S . -B build
    - name: Build
      run: cmake --build build
